### PR TITLE
Release note for adding Spanish ENS standard

### PR DESCRIPTION
**Pull request by memildin**

### CODE REVIEW

**Comment by memildin** [comment]
#sign-off

**Comment by memildin** [comment]
@dcurwin I'm happy for this to be merged as soon as you've reviewed it. TIA.

**Comment by dcurwin** [comment]
#sign-off

**Comment by memildin** [comment]
#sign-off

**Comment by memildin** [comment]
Closing. Made this in the wrong repo.
Replaced with https://github.com/MicrosoftDocs/azure-security-docs-pr/pull/132

**Pull request closed without merging**
