### PR TITLE
Added Futurex to the Supported HSMs list

### PR DESCRIPTION
**Pull request by AdamCason**

### CODE REVIEW

**Comment by Court72** [comment]
@msmbaldwin

Can you review the proposed changes? 
	
**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 
	
#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by msmbaldwin** [comment]
Hello, @adamCason. We can add Futurex to the list if supported HSMs if you have implemented BYOK on your end. Can you verify that this is the case?

**Comment by AdamCason** [comment]
> Hello, @AdamCason. We can add Futurex to the list if supported HSMs if you have implemented BYOK on your end. Can you verify that this is the case?

Thanks for following up on this, and yes, I can confirm that we have implemented BYOK. Happy to share any background information or documentation needed, or set up a demo if you'd like - I'm available at acason@futurex.com.

**Comment by msmbaldwin** [comment]
Thanks, @AdamCason. I will get this merged! #sign-off

**Pull request merged**
