### PR TITLE
Fixed role assignment in code samples

### PR DESCRIPTION
**Pull request by navid-ahrary**
The role assignments are wrong in all code samples.
For creating a new key, secret, and certificate; the user's role must be  "Key Vault Officer" roles, not "Key Vault User"!
"Key Vault User" is just for read access, not write access.

### CODE REVIEW

**Comment by navid-ahrary** [comment]
@microsoft-github-policy-service agree

**Comment by Jak-MS** [comment]
@duffney @msmbaldwin 
Can you review the proposed changes? 

**Important**: When the changes are ready for publication, adding a `#sign-off` comment is the best way to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by navid-ahrary** [comment]
#sign-off

**Comment by duffney** [comment]
#sign-off

**Comment by Jak-MS** [comment]
Thanks @duffney !  

Still waiting on @msmbaldwin to approve the changes to his articles.  

@msmbaldwin - can you sign off when you've reviewed and approved? thanks.

**Comment by navid-ahrary** [comment]
any news?

**Comment by msmbaldwin** [comment]
Thank you for this, @navid-ahrary! This is an important fix, and we appreciate you taking the time to improve our documentation. #sign-off

**Pull request merged**
